Product uploading workflow
Pronovix/videogame pull request #26
Opened 2020-04-13 17:06 UTC by ilci

Add further infos to product_uploader.info.yml and write the product_uploader.module. Activate the module on the site.

2020-04-14 07:21 UTC, tamasd requested changes

2020-04-14 07:21 UTC, tamasd commented on web/modules/custom/product_uploader/product_uploader.module
> +  $fragment = '+productuploader';
Move this to a constant outside of this function using the `const` keyword. Prefix the constant's name with the module's name. It should be something like `PRODUCT_UPLOADER_FRAGMENT`.

2020-04-14 07:21 UTC, tamasd commented on web/modules/custom/product_uploader/product_uploader.module
> +    $entity->addRole('product_uploader');
Move the name of the role into a constant.

2020-04-14 07:21 UTC, tamasd commented on web/modules/custom/product_uploader/product_uploader.module
> +    $entity->removeRole('product_uploader');
Move the name of the role into a constant.

2020-04-14 07:21 UTC, tamasd commented on web/modules/custom/product_uploader/product_uploader.module
> +/*https://red-route.org/articles/adding-roles-user-programmatically-drupal-8
Remove comment.

2020-04-16 11:05 UTC, tamasd requested changes

2020-04-16 11:05 UTC, tamasd commented on web/modules/custom/product_uploader/src/ProductUploaderInterface.php
> +class ProductUploaderInterface {
Is this a class or an interface?

I think this should be a `final class` with an empty private constructor: https://stackoverflow.com/a/53194084

2020-04-16 12:46 UTC, tamasd approved these changes

2020-04-16 13:15 UTC, kittiradovics approved these changes

2020-04-16 15:50 UTC, merged