Add Product API to User timezone module
Pronovix/videogame pull request #37
Opened 2020-04-22 14:25 UTC by andretothie

Adding the recommendation block, the recommendation controller, and the recommendation routing

2020-04-23 12:52 UTC, tamasd requested changes

2020-04-23 12:52 UTC, tamasd commented on web/modules/custom/user_timezone/src/Controller/UserTimezoneRecommendationController.php
> +  protected $queryFactory;
You don't need this

2020-04-23 12:52 UTC, tamasd commented on web/modules/custom/user_timezone/src/Controller/UserTimezoneRecommendationController.php
> +    );
```suggestion
    return new JsonResponse($this->getData());
```

2020-04-23 12:52 UTC, tamasd commented on web/modules/custom/user_timezone/src/Controller/UserTimezoneRecommendationController.php
> +      ->condition('field_tags.entity.name', 'session time')
Why is this condition needed? I think you want to do something else here.

2020-04-23 12:52 UTC, tamasd commented on web/modules/custom/user_timezone/src/Controller/UserTimezoneRecommendationController.php
> +        $node = $this->entityTypeManager->getStorage('node_id');
Move the loading outside of the foreach. You want to load all nodes at the same time, like this:

```php
$nodes = $this->entityTypeManager->getStorage('node')->loadMultiple($nids);
```

Then you foreach over the `$nodes` array to construct the `$result` array.

2020-04-28 08:32 UTC, tamasd requested changes

2020-04-28 08:32 UTC, tamasd commented on web/modules/custom/user_timezone/src/Controller/UserTimezoneRecommendationController.php
> +      $firstItem = reset($node);
```suggestion
      $firstItem = $node[array_rand($node, 1)];
```

2020-04-28 08:32 UTC, tamasd commented on web/modules/custom/user_timezone/src/Controller/UserTimezoneRecommendationController.php
> +  protected $entityTypeManager;
You don't need the whole entity type manager, you can inject just the node storage.

2020-04-28 08:32 UTC, tamasd commented on web/modules/custom/user_timezone/src/Controller/UserTimezoneRecommendationController.php
> +class UserTimezoneRecommendationController extends ControllerBase {
The class can be final

2020-04-28 08:32 UTC, tamasd commented on web/modules/custom/user_timezone/src/Plugin/Block/UserTimezoneRecommendationBlock.php
> +class UserTimezoneRecommendationBlock extends BlockBase implements ContainerFactoryPluginInterface {
This class can be final

2020-04-28 08:32 UTC, tamasd commented on web/modules/custom/user_timezone/src/Plugin/Block/UserTimezoneRecommendationBlock.php
> +  public function build() {
Missing return type `array`

2020-04-28 08:32 UTC, tamasd commented on web/modules/custom/user_timezone/src/UserTimezoneRecommendation.php
> +class UserTimezoneRecommendation {
This class can be final

2020-04-28 08:32 UTC, tamasd commented on web/modules/custom/user_timezone/src/Controller/UserTimezoneRecommendationController.php
> +      ];
```suggestion
      return new JsonResponse([
        'Product name' => $firstItem->label(),
        'url' => $firstItem->toUrl()->toString(),
      ]);
```

2020-04-28 08:32 UTC, tamasd commented on web/modules/custom/user_timezone/src/Controller/UserTimezoneRecommendationController.php
> +    ];
```suggestion
```

2020-04-28 08:32 UTC, tamasd commented on web/modules/custom/user_timezone/src/Controller/UserTimezoneRecommendationController.php
> +    return new JsonResponse($json_array);
```suggestion
    return new JsonResponse(new stdClass());
```

2020-04-29 13:32 UTC, tamasd requested changes

2020-04-29 13:32 UTC, tamasd commented on web/modules/custom/user_timezone/src/Controller/UserTimezoneRecommendationController.php
> +    $this->entityTypeManager = $entityTypeManager;
```suggestion
  public function __construct(EntityStorageInterface $nodeStorage, EntityStorageInterface $termStorage, UserTimezoneSalutation $salutation) {
    $this->nodeStorage = $nodeStorage;
    $this->termStorage = $termStorage;
```

2020-04-29 13:32 UTC, tamasd commented on web/modules/custom/user_timezone/src/Controller/UserTimezoneRecommendationController.php
> +
```suggestion
private $nodeStorage;
private $termStorage;
```

and add proper comments

2020-04-29 13:32 UTC, tamasd commented on web/modules/custom/user_timezone/src/Controller/UserTimezoneRecommendationController.php
> +    $query = $this->entityTypeManager->getStorage('node')->getQuery();
```suggestion
    $query = $this->nodeStorage->getQuery();
```

2020-04-29 13:32 UTC, tamasd commented on web/modules/custom/user_timezone/src/Controller/UserTimezoneRecommendationController.php
> +      $node = $this->entityTypeManager->getStorage('node')->loadMultiple($nids);
```suggestion
      $node = $this->nodeStorage->loadMultiple($nids);
```

2020-04-29 13:32 UTC, tamasd commented on web/modules/custom/user_timezone/src/Controller/UserTimezoneRecommendationController.php
> +    );
```suggestion
    $entityTypeManager = $container->get('entity_type.manager');
    return new static(
      $entityTypeManager->getStorage('node'),
      $entityTypeManager->getStorage('taxonomy_term'),
      $container->get('user_timezone.salutation')
    );
```

2020-04-29 13:32 UTC, tamasd commented on web/modules/custom/user_timezone/src/Controller/UserTimezoneRecommendationController.php
> +    $terms = $this->entityTypeManager->getStorage('taxonomy_term')->loadByProperties([
```suggestion
    $terms = $this->termStorage->loadByProperties([
```

2020-04-29 13:32 UTC, tamasd commented on web/modules/custom/user_timezone/src/Controller/UserTimezoneRecommendationController.php
> +
```suggestion
```

2020-04-30 06:38 UTC, tamasd approved these changes

2020-04-30 09:06 UTC, kittiradovics approved these changes

2020-04-30 09:10 UTC, merged