add Product CT
Pronovix/videogame pull request #4
Opened 2020-03-19 16:11 UTC by Rolligta

2020-03-20 08:08 UTC, kittiradovics requested changes

2020-03-20 08:08 UTC, kittiradovics commented on config/sync/field.field.node.product.field_genres.yml
> +field_type: list_string
The genres field should be a plain text area, so list field type is not suitable here.

2020-03-20 08:43 UTC, kittiradovics requested changes

2020-03-20 08:43 UTC, kittiradovics commented on config/sync/field.storage.node.field_genres.yml
> +cardinality: -1
Why multivalue?

2020-03-23 09:47 UTC, kittiradovics approved these changes

2020-03-23 09:48 UTC, tamasd approved these changes

2020-03-23 09:48 UTC, merged