Fine tune product page, genre taxonomy and similar games views
Pronovix/videogame pull request #42
Opened 2020-04-27 13:22 UTC by szucsanAndras

- Create and theme genres taxonomy term view
- Add product content type filter to similar games view 
- Remove genres field from product display

2020-04-27 13:39 UTC, kittiradovics requested changes

2020-04-27 13:39 UTC, kittiradovics commented on web/themes/custom/subtheme_videogame/src/components/node/block--views-block--games-of-similar-genre-block-1.html.twig
> +      <h2 class="product__similar-games-title"{{ title_attributes }}>{{ label }}</h2>
Please use `title_attributes.addClass('xyz')` for adding a new class.

2020-04-28 10:54 UTC, kittiradovics approved these changes

2020-04-28 10:56 UTC, tamasd approved these changes

2020-04-28 11:41 UTC, merged