Issue/7897
Pronovix/videogame pull request #5
Opened 2020-03-20 08:59 UTC by ilci

2020-03-20 16:17 UTC, kittiradovics requested changes

2020-03-20 16:17 UTC, kittiradovics commented on .unicompilerc.json
> +    "cwd": "web/themes/custom/subtheme_videogame"
This file is not needed as you will use the built-in compiler in the theme.

2020-03-20 16:17 UTC, kittiradovics commented on web/themes/custom/subtheme_videogame/src/sass/base/_variables.scss
> +$input-btn-font-family:       Montserrat !default;
Is this font type is available by default from the theme? I'm asking because I can't see any font files in your theme.

2020-03-20 16:17 UTC, kittiradovics commented on web/themes/custom/subtheme_videogame/src/sass/base/_variables.scss
> +$font-family-sans-serif:      Open-Sans !default;
Is this font type is available by default from the theme? I'm asking because I can't see any font files in your theme.

2020-03-20 16:17 UTC, kittiradovics commented on web/themes/custom/subtheme_videogame/src/sass/base/_variables.scss
> +$body-bg:                   $black !default;
Please remove `!default` after the variables you are modifying as these values are overrides.

2020-03-20 16:17 UTC, kittiradovics commented on web/themes/custom/subtheme_videogame/webpack.mix.js
> +mix.browserSync({
Please remove this part of the file as Gabor suggested.

2020-03-23 08:04 UTC, kittiradovics approved these changes

2020-03-23 08:07 UTC, tamasd approved these changes

2020-03-23 09:09 UTC, merged