remove the subtheme_videogame.style.css from assets folder (with git …
Pronovix/videogame pull request #6
Opened 2020-03-23 17:09 UTC by ilci

…rm -f), add web/themes/custom/**/*.css to.gitignore file.

2020-03-25 16:00 UTC, kittiradovics requested changes

2020-03-25 16:00 UTC, kittiradovics commented on web/themes/custom/subtheme_videogame/src/components/navbar/navbar.twig
> +  {% endif %}
Where's `{% if ... %}` statement?

2020-03-25 16:00 UTC, kittiradovics commented on web/themes/custom/subtheme_videogame/src/sass/base/_mixins.scss
> +
Please remove the unnecessary extra lines.

2020-03-25 16:00 UTC, kittiradovics commented on web/themes/custom/subtheme_videogame/src/sass/base/_mixins.scss
> +.navbar{
Please add space before opening brace.

2020-03-25 16:00 UTC, kittiradovics commented on web/themes/custom/subtheme_videogame/src/sass/base/_mixins.scss
> +$orange: #F57C00;
Please place the colors in a separate `_colors.scss` file and import it before the import of `_variables.scss`.

2020-03-25 16:00 UTC, kittiradovics commented on web/themes/custom/subtheme_videogame/src/components/navbar/navbar.twig
> +{#
Please remove this file if haven't changed anything in it.

2020-03-25 16:00 UTC, kittiradovics commented on composer.lock
> +        {
Bootstrap theme should be removed. Uninstall the Bootstrap theme if you haven't yet done so (on Appearance page) and use `composer remove drupal/bootstrap`.

2020-03-25 16:00 UTC, kittiradovics commented on composer.lock
> +        {
And please don't forget to export your configuration to enable your new theme.

2020-03-25 16:00 UTC, kittiradovics commented on web/themes/custom/subtheme_videogame/src/sass/base/_elements.scss
> +.nav-link{
Please remove the unnecessary extra lines.

2020-03-25 16:00 UTC, kittiradovics commented on web/themes/custom/subtheme_videogame/src/sass/base/_elements.scss
> +
The navbar related theming should go inside components folder.

2020-03-25 16:00 UTC, kittiradovics commented on web/themes/custom/subtheme_videogame/src/sass/base/_mixins.scss
> +.navbar{
This part can go into the navbar theming file.

2020-03-26 07:32 UTC, kittiradovics requested changes

2020-03-26 07:32 UTC, kittiradovics commented on web/themes/custom/subtheme_videogame/src/sass/base/_variables.scss
> +$orange:  #F57C00;
As you have already created a `_colors.scss` file, you can move every color definition to that file to have every color in a single place.

2020-03-26 07:32 UTC, kittiradovics commented on web/themes/custom/subtheme_videogame/src/components/navbar/_navbar.scss
> +.nav-link{
Please add space before the opening curly brace.

2020-03-26 07:32 UTC, kittiradovics commented on web/themes/custom/subtheme_videogame/src/components/navbar/_navbar.scss
> +.navbar-brand{
Please add space before the opening curly brace.

2020-03-26 07:32 UTC, kittiradovics commented on composer.lock
> -            "name": "drupal/bootstrap",
`composer.json` related changes are missing.

2020-03-26 12:42 UTC, kittiradovics approved these changes

2020-03-26 12:44 UTC, tamasd approved these changes

2020-03-26 12:46 UTC, merged